# Generated by Django 5.0.2 on 2024-02-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Кошик Користувача',
                'verbose_name_plural': 'Кошик',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ChoiceProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Продукт')),
                ('choice_slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Тип Продукту',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CompanyProducingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Компанія виробник')),
                ('company_slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Компанію Виробник',
                'verbose_name_plural': 'Компанії Виробники',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CompleteCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cart', models.CharField(max_length=255, verbose_name='Готовий набір')),
                ('price_cart', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Ціна')),
                ('weight_cart', models.IntegerField(verbose_name='Вага')),
                ('about_cart', models.TextField(verbose_name='Про товар')),
                ('photo_cart', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('expiration_date_cart', models.CharField(max_length=255, verbose_name='Термін Придатності')),
                ('composition_cart', models.CharField(max_length=255, verbose_name='Склад Кошика')),
            ],
            options={
                'verbose_name': 'Готовий Набір',
                'verbose_name_plural': 'Готові Набори',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CountryProducingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Країна виробник')),
                ('country_slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Країну Виробник',
                'verbose_name_plural': 'Країни Виробник',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name="Ім'я Продукту")),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Ціна')),
                ('weight', models.IntegerField(verbose_name='Вага')),
                ('about', models.TextField(verbose_name='Про товар')),
                ('expiration_date', models.CharField(max_length=255, verbose_name='Термін Придатності')),
                ('ingredient', models.CharField(max_length=255, null=True, verbose_name='Склад товару')),
                ('availability', models.BooleanField(default=True, verbose_name='Наявність')),
                ('publication', models.BooleanField(default=True, verbose_name='Публікація')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Органічна Продукція',
                'verbose_name_plural': 'Органічна Продукція',
                'ordering': ['-id'],
            },
        ),
    ]
